# pytest.ini
[pytest]
addopts =
  -v
  --cache-clear
  --capture=no
console_output_style = count
python_classes = *Tests
python_files = *_tests.py
python_functions = *_test
testpaths = tests
markers = 
  unit: marks tests as unit tests
  integration: marks tests as integration tests
